### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by sayaendo** [HendrikStrobelt/Seq2Seq-Vis#20]
Hi, the demo on http://seq2seq-vis.io is not currently working - it gets stuck when requesting translation. I'm interested in using the demo to present your work to colleagues. Thanks

**Comment by HendrikStrobelt** [comment]
@sayaendo Thank you for pointing this out. We will have a closer look why it randomly crashes. I restarted and it works again.

**Comment by sayaendo** [comment]
It's down now again, if that will help you find out why that happens (and if possible restart it again :))

**Comment by HendrikStrobelt** [comment]
Thanks for pinging.. The error is a tricky one, as it occurs only rarely but then deadly :) Thanks for keeping on to it.
