### ISSUE TITLE
Running h5_to_faiss.py script fails with invalid ELF header on swigfaiss.so

### ISSUE THREAD

**Issue by mohammedayub44** [HendrikStrobelt/Seq2Seq-Vis#31]
@HendrikStrobelt 

I have generated the states.h5 file and now want to create the indices for encoder and decoder. Running the `h5_to_faiss.py` script fails on `_swigfaiss.so` with  invalid ELF header.

I have tried reinstalling the faiss library, installing different versions of faiss library, also gpu version and they don't seem to solve the original problem.

It seems like `_swigfaiss.so` is corrupted, if so, is there a location where i can download latest version from.

Is there any alternate workaround for generating the indices apart from using this scrips ?

Snapshot of Error:
![image](https://user-images.githubusercontent.com/7122670/66053354-2b41bd00-e500-11e9-9d2a-12501e71a46d.png)

Thanks !

Mohammed Ayub

**Comment by mohammedayub44** [comment]
Presently I just got around this error by installing faiss in another conda environment. Running only those lines from `h5_to_faiss.py` that extract the indices and context separately in Jupyter notebook. Successfully generated those 3 files (encoder.faiss, decoder.faiss and context.faiss)
Assuming we don't require the swigfaiss files in the same folder.

**Comment by Leslie-Fang** [comment]
@mohammedayub44  Can you show more details about how to get around this error? Thanks

**Comment by mohammedayub44** [comment]
@Leslie-Fang 
If you look at the `h5_to_faisss.py` all we need the faiss library installed (version)
`conda install -c pytorch faiss-cpu`  this should install [version ](https://anaconda.org/pytorch/faiss-cpu/files)`1.6.0` in your new environment. As long as you can run `import faiss` you can run the below step.

I just wanted to see what each step is doing so I broke it out in the Jupyter file like below (running it three times for different outputs as suggested [here](https://github.com/HendrikStrobelt/Seq2Seq-Vis#prepare-and-run-own-models) 

![image](https://user-images.githubusercontent.com/7122670/67325661-7f2e3900-f4e3-11e9-83aa-92a2915515dc.png)


Hope that helps.

**Comment by leslie-fang-intel** [comment]
@mohammedayub44 Thanks for the information
It seems faiss.py in the scripts is useless. Remove it would fix the problem

**Comment by Leslie-Fang** [comment]
@mohammedayub44 Thanks for the information
It seems faiss.py in the scripts is useless. Remove it would fix the problem
